"""
Intake Routes - Handle victim assessment submissions

POST /assess: Accept text or voice input, analyze, store case, return results
"""

from fastapi import APIRouter, Depends, HTTPException, Request
from pydantic import BaseModel
from sqlalchemy.orm import Session
from app.database.db import get_db
from app.database.models import Case
from app.services.ai_assessment import generate_full_assessment
from app.services.speech_to_text import transcribe_audio
from app.services.voice_analyzer import analyze_voice
from app.utils.anonymize import generate_case_id, mask_transcript_excerpt
from app.utils.logger import log_event
import base64

router = APIRouter(prefix="/api", tags=["intake"])


class AssessmentRequest(BaseModel):
    """Assessment submission from victim."""
    text: str = None  # Direct text input
    audio_base64: str = None  # Voice note as base64
    language: str = "en"  # Language code: 'en' or 'hi'


class AssessmentResponse(BaseModel):
    """Response returned after assessment."""
    case_id: str
    svi_score: float
    category: str
    recommended_action: str
    analysis_breakdown: dict
    ai_report: str = None  # Gemini-generated human-readable case summary


@router.post("/assess", response_model=AssessmentResponse)
async def submit_assessment(
    request: AssessmentRequest,
    db: Session = Depends(get_db),
    req: Request = None,
) -> AssessmentResponse:
    """
    Submit text or voice for assessment.

    Flow:
    1. Validate input (text or audio)
    2. Transcribe audio if provided (or use text directly)
    3. Analyze voice features if audio provided (currently informational only —
       not yet fed into the Gemini prompt; see note below)
    4. Generate full assessment via Gemini in a single call: score, category,
       recommended action, breakdown, and narrative report
       (app/services/ai_assessment.py — generate_full_assessment)
    5. Store case in database
    6. Return results

    PRIVACY NOTE: Audio is NOT stored. After transcription and voice analysis,
    the audio bytes are discarded (not persisted).

    NOTE ON SCORING: The SVI score, category, recommended action, and narrative
    report are now ALL generated by a single Gemini call (generate_full_assessment).
    A deterministic crisis-keyword safety net inside that function overrides Gemini's
    category/score to "Critical" if configured high-risk terms are present in the
    transcript, regardless of what Gemini returned — this keeps the single most
    safety-critical decision auditable and not solely dependent on the LLM.

    NOTE ON VOICE FEATURES: voice_features (pitch/pause/energy) is currently computed
    but not yet passed into the Gemini prompt. If you want voice signals to influence
    the score, that needs to be added as an explicit parameter to
    generate_full_assessment and reflected in the prompt — flagging this so it doesn't
    silently look "wired up" when it isn't yet.
    """

    # Validate: must have either text or audio
    if not request.text and not request.audio_base64:
        raise HTTPException(status_code=400, detail="Must provide either text or audio")

    # Get client IP for audit trail
    client_ip = req.client.host if req else None

    # Transcribe audio or use provided text
    transcript = request.text
    voice_features = None

    if request.audio_base64:
        try:
            # Decode audio from base64
            audio_bytes = base64.b64decode(request.audio_base64)

            # Transcribe to text (Whisper API call — see speech_to_text.py)
            transcript = transcribe_audio(audio_bytes)

            # Analyze voice features
            voice_features = analyze_voice(audio_bytes)

            # === CRITICAL: AUDIO DELETION ===
            # After transcription and analysis, the audio_bytes variable will go out of scope
            # and be garbage collected. No raw audio is stored in the database.
            # This is essential for privacy—we do not want voice samples on disk.
            # =============================

            log_event(
                "voice_processed",
                {
                    "case_ip": client_ip,
                    "has_voice": True,
                    "voice_features": voice_features,
                },
            )

        except Exception as e:
            log_event(
                "voice_processing_failed",
                {"error": str(e), "client_ip": client_ip},
                level="ERROR",
            )
            raise HTTPException(status_code=400, detail=f"Audio processing failed: {str(e)}")

    # Generate full assessment via Gemini (score + category + action + breakdown + report,
    # with deterministic crisis-keyword safety net applied inside)
    assessment = generate_full_assessment(transcript, request.language)

    # Create anonymized case ID
    case_id = generate_case_id(transcript)

    # Mask transcript excerpt for storage
    transcript_excerpt = mask_transcript_excerpt(transcript, max_length=500)

    # Store in database
    case = Case(
        case_id=case_id,
        language=request.language,
        transcript_excerpt=transcript_excerpt,
        svi_score=assessment["svi_score"],
        category=assessment["category"],
        recommended_action=assessment["recommended_action"],
        analysis_breakdown=assessment["breakdown"],
        ai_report=assessment["report"],
        created_ip=client_ip,
    )
    db.add(case)
    db.commit()
    db.refresh(case)

    log_event(
        "assessment_submitted",
        {
            "case_id": case_id,
            "category": assessment["category"],
            "svi_score": assessment["svi_score"],
            "client_ip": client_ip,
        },
    )

    return AssessmentResponse(
        case_id=case_id,
        svi_score=assessment["svi_score"],
        category=assessment["category"],
        recommended_action=assessment["recommended_action"],
        analysis_breakdown=assessment["breakdown"],
        ai_report=assessment["report"],
    )


@router.get("/health")
async def health_check():
    """Simple health check endpoint."""
    return {"status": "ok", "service": "sahai-intake"}