import { useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import CriticalSafetyNotice from '../components/CriticalSafetyNotice';
import PatientChatWidget from '../components/PatientChatWidget';

export default function AssessmentResults() {
  const location = useLocation();
  const navigate = useNavigate();
  const { t } = useTranslation();
  const result = location.state?.result;
  const [expandedSection, setExpandedSection] = useState('overview');
  const [showChat, setShowChat] = useState(false);

  if (!result) {
    return (
      <div className="min-h-screen bg-white flex items-center justify-center">
        <div className="text-center">
          <p className="text-gray-600 mb-4">No assessment data found</p>
          <button
            onClick={() => navigate('/intake')}
            className="btn-primary"
          >
            Back to Assessment
          </button>
        </div>
      </div>
    );
  }

  const getCategoryColor = (category) => {
    const colors = {
      Low: 'bg-green-50 border-green-200 text-green-800',
      Moderate: 'bg-yellow-50 border-yellow-200 text-yellow-800',
      High: 'bg-orange-50 border-orange-200 text-orange-800',
      Critical: 'bg-red-50 border-red-200 text-red-800',
    };
    return colors[category] || 'bg-gray-50 border-gray-200 text-gray-800';
  };

  const getCategoryBadgeColor = (category) => {
    const colors = {
      Low: 'bg-green-100 text-green-800',
      Moderate: 'bg-yellow-100 text-yellow-800',
      High: 'bg-orange-100 text-orange-800',
      Critical: 'bg-red-100 text-red-800',
    };
    return colors[category] || 'bg-gray-100 text-gray-800';
  };

  const getScoreColor = (score, maxScore = 100) => {
    const percent = (score / maxScore) * 100;
    if (percent <= 25) return 'text-green-600';
    if (percent <= 50) return 'text-yellow-600';
    if (percent <= 75) return 'text-orange-600';
    return 'text-red-600';
  };

  // Render a progress bar for factor scores
  const FactorBar = ({ label, score, max = 100 }) => {
    const percent = (score / max) * 100;
    const color = percent <= 25 ? 'bg-green-500' : percent <= 50 ? 'bg-yellow-500' : percent <= 75 ? 'bg-orange-500' : 'bg-red-500';

    return (
      <div className="mb-4">
        <div className="flex justify-between items-center mb-1">
          <span className="text-sm font-medium text-gray-700">{label}</span>
          <span className={`text-sm font-semibold ${getScoreColor(score, max)}`}>{score.toFixed(1)}</span>
        </div>
        <div className="w-full bg-gray-200 rounded-full h-2.5">
          <div
            className={`h-2.5 rounded-full ${color} transition-all duration-300`}
            style={{ width: `${percent}%` }}
          ></div>
        </div>
      </div>
    );
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-white flex flex-col">
      {/* Navbar */}
      <nav className="border-b border-gray-200 bg-white shadow-sm">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-10 h-10 bg-blue-600 rounded-full flex items-center justify-center">
              <span className="text-white font-bold text-lg">S</span>
            </div>
            <span className="text-xl font-bold text-gray-900">SahAI</span>
          </div>
          <div className="flex items-center gap-6">
            <button
              onClick={() => navigate('/psychiatrist/login')}
              className="text-gray-600 hover:text-blue-600 font-medium transition-colors"
            >
              Psychiatrist Portal
            </button>
            <button
              onClick={() => navigate('/')}
              className="text-gray-600 hover:text-gray-900 transition"
            >
              ← Back
            </button>
          </div>
        </div>
      </nav>

      {/* Main Content */}
      <div className="flex-1 px-6 py-12">
        <div className="max-w-4xl mx-auto">
          {/* Header */}
          <div className="mb-8">
            <h1 className="text-4xl font-bold text-gray-900 mb-2">
              Assessment Report
            </h1>
            <p className="text-gray-600">
              Generated by AI Assessment System · Case ID: <span className="font-mono text-gray-800">{result.case_id}</span>
            </p>
          </div>

          {/* Immediate Safety Response for Critical SVI Patients */}
          {(result.category === 'Critical' || result.is_critical || (result.svi_score >= 76)) && (
            <CriticalSafetyNotice
              caseId={result.case_id}
              onOpenChat={() => setShowChat(true)}
            />
          )}

          {/* SVI Score Card - Featured */}
          <div className={`border-2 rounded-2xl p-8 mb-8 ${getCategoryColor(result.category)} shadow-lg`}>
            <div className="flex items-start justify-between mb-6">
              <div>
                <p className="text-sm font-semibold opacity-75 mb-2 uppercase tracking-wide">Stress Vulnerability Index</p>
                <div className="flex items-baseline gap-2">
                  <span className="text-7xl font-bold">{result.svi_score?.toFixed(1)}</span>
                  <span className="text-2xl opacity-70">/100</span>
                </div>
              </div>
              <div className={`inline-block px-6 py-3 rounded-full font-bold text-lg ${getCategoryBadgeColor(result.category)}`}>
                {result.category?.toUpperCase()}
              </div>
            </div>

            {/* Status message */}
            <div className="text-sm mt-4 pt-4 border-t border-current opacity-75">
              {result.category === 'Critical' && '⚠️ Flagged for immediate human review'}
              {result.category === 'High' && '⚠️ Requires urgent counsellor consultation'}
              {result.category === 'Moderate' && 'Counsellor callback can be arranged'}
              {result.category === 'Low' && 'Self-help resources available'}
            </div>
          </div>

          {/* Recommended Action Box */}
          {result.recommended_action && (
            <div className="bg-blue-50 border-l-4 border-blue-500 rounded-lg p-6 mb-8">
              <h3 className="text-sm font-bold text-blue-900 uppercase mb-2">Recommended Action</h3>
              <p className="text-lg text-blue-900 font-medium">
                {result.recommended_action}
              </p>
            </div>
          )}

          {/* Analysis Breakdown - Detailed Metrics */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8">
            {/* Left Column - Factor Scores */}
            <div className="bg-white rounded-xl shadow-md p-6 border border-gray-200">
              <h3 className="text-xl font-bold text-gray-900 mb-6 flex items-center gap-2">
                <span className="text-2xl">📊</span> Assessment Factors
              </h3>

              {result.analysis_breakdown && (
                <div className="space-y-6">
                  <FactorBar
                    label="Emotional Intensity"
                    score={result.analysis_breakdown.emotional_intensity || 0}
                  />
                  <FactorBar
                    label="Sentiment Analysis"
                    score={Math.max(0, (result.analysis_breakdown.sentiment || 0) + 100) / 2}
                  />
                  <FactorBar
                    label="Crisis Indicators"
                    score={result.analysis_breakdown.crisis_indicators || 0}
                  />
                  <FactorBar
                    label="Narrative Severity"
                    score={result.analysis_breakdown.narrative_severity || 0}
                  />
                </div>
              )}
            </div>

            {/* Right Column - Factor Cards */}
            <div className="bg-white rounded-xl shadow-md p-6 border border-gray-200">
              <h3 className="text-xl font-bold text-gray-900 mb-6 flex items-center gap-2">
                <span className="text-2xl">📈</span> Breakdown Summary
              </h3>

              {result.analysis_breakdown ? (
                <div className="space-y-4">
                  <div className="bg-gradient-to-br from-purple-50 to-purple-100 rounded-lg p-4">
                    <p className="text-xs font-semibold text-purple-700 uppercase">Emotional Intensity</p>
                    <p className="text-3xl font-bold text-purple-900">{result.analysis_breakdown.emotional_intensity?.toFixed(0)}</p>
                  </div>
                  <div className="bg-gradient-to-br from-blue-50 to-blue-100 rounded-lg p-4">
                    <p className="text-xs font-semibold text-blue-700 uppercase">Sentiment</p>
                    <p className="text-3xl font-bold text-blue-900">{result.analysis_breakdown.sentiment?.toFixed(0)}</p>
                  </div>
                  <div className="bg-gradient-to-br from-orange-50 to-orange-100 rounded-lg p-4">
                    <p className="text-xs font-semibold text-orange-700 uppercase">Crisis Indicators</p>
                    <p className="text-3xl font-bold text-orange-900">{result.analysis_breakdown.crisis_indicators?.toFixed(0)}</p>
                  </div>
                  <div className="bg-gradient-to-br from-red-50 to-red-100 rounded-lg p-4">
                    <p className="text-xs font-semibold text-red-700 uppercase">Narrative Severity</p>
                    <p className="text-3xl font-bold text-red-900">{result.analysis_breakdown.narrative_severity?.toFixed(0)}</p>
                  </div>
                </div>
              ) : (
                <p className="text-gray-500">No detailed breakdown available</p>
              )}
            </div>
          </div>

          {/* AI Generated Report */}
          {result.ai_report && (
            <div className="bg-white rounded-xl shadow-md p-8 mb-8 border border-gray-200">
              <h3 className="text-2xl font-bold text-gray-900 mb-4 flex items-center gap-2">
                <span className="text-2xl">🤖</span> AI Analysis Report
              </h3>
              <div className="prose prose-sm max-w-none">
                <p className="text-gray-700 leading-relaxed text-base whitespace-pre-wrap">
                  {result.ai_report}
                </p>
              </div>
              <div className="mt-4 pt-4 border-t border-gray-200 text-xs text-gray-500">
                Generated by Gemini AI • Not a clinical diagnosis • For counsellor review only
              </div>
            </div>
          )}

          {/* Collapsible Sections for Additional Details */}
          <div className="space-y-4 mb-8">
            {/* Full Data Section */}
            <div className="bg-white rounded-xl shadow-md border border-gray-200 overflow-hidden">
              <button
                onClick={() => setExpandedSection(expandedSection === 'details' ? null : 'details')}
                className="w-full px-6 py-4 flex items-center justify-between hover:bg-gray-50 transition"
              >
                <h3 className="text-lg font-bold text-gray-900 flex items-center gap-2">
                  <span className="text-xl">📋</span> Full Assessment Data
                </h3>
                <span className={`text-gray-600 transition-transform ${expandedSection === 'details' ? 'rotate-180' : ''}`}>
                  ▼
                </span>
              </button>

              {expandedSection === 'details' && (
                <div className="px-6 py-4 bg-gray-50 border-t border-gray-200">
                  <pre className="bg-gray-900 text-gray-100 rounded p-4 overflow-auto text-xs max-h-64">
                    {JSON.stringify(result, null, 2)}
                  </pre>
                </div>
              )}
            </div>
          </div>

          {/* Action Buttons */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8">
            <button
              onClick={() => navigate('/intake')}
              className="btn-primary py-3 rounded-lg font-semibold hover:shadow-lg transition"
            >
              ← New Assessment
            </button>
            <button
              onClick={() => navigate('/dashboard')}
              className="btn-secondary py-3 rounded-lg font-semibold hover:shadow-lg transition"
            >
              📊 View Dashboard
            </button>
            <button
              onClick={() => {
                const element = document.createElement('a');
                const file = new Blob([JSON.stringify(result, null, 2)], {type: 'application/json'});
                element.href = URL.createObjectURL(file);
                element.download = `assessment-${result.case_id}.json`;
                document.body.appendChild(element);
                element.click();
                document.body.removeChild(element);
              }}
              className="btn-secondary py-3 rounded-lg font-semibold hover:shadow-lg transition"
            >
              ⬇️ Export Report
            </button>
          </div>

          {/* Information Box */}
          <div className="bg-blue-50 rounded-xl p-6 border border-blue-200 mb-8">
            <h3 className="font-bold text-blue-900 mb-3 flex items-center gap-2">
              <span>ℹ️</span> What Happens Next
            </h3>
            <ul className="space-y-2 text-sm text-blue-900">
              <li className="flex items-start gap-3">
                <span className="text-lg">✓</span>
                <span><strong>Confidential Storage:</strong> Your assessment is securely recorded and anonymized</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="text-lg">✓</span>
                <span><strong>Human Review:</strong> A trained counsellor will review your case promptly</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="text-lg">✓</span>
                <span><strong>Follow-up Support:</strong> You will receive appropriate support and resources</span>
              </li>
              <li className="flex items-start gap-3">
                <span className="text-lg">✓</span>
                <span><strong>Privacy Assured:</strong> All conversations remain confidential and anonymous</span>
              </li>
            </ul>
          </div>
        </div>
      </div>

      {/* Floating Chat Modal */}
      {showChat && (
        <div className="fixed bottom-6 right-6 z-50">
          <PatientChatWidget
            caseId={result.case_id}
            senderType="patient"
            senderName="Patient"
            onClose={() => setShowChat(false)}
          />
        </div>
      )}

      {/* Footer */}
      <footer className="border-t border-gray-200 bg-white py-8 mt-auto">
        <div className="max-w-7xl mx-auto px-6 text-center text-sm text-gray-600">
          <p>{t('footer.disclaimer')}</p>
          <p className="mt-2 text-xs text-gray-500">Case ID: {result.case_id}</p>
        </div>
      </footer>
    </div>
  );
}
