import React from 'react';
import { useNavigate } from 'react-router-dom';

export default function HowItWorks() {
  const navigate = useNavigate();

  const steps = [
    {
      number: '01',
      title: 'Consent, first',
      description:
        "Before anything is analyzed, you're told exactly what happens to what you say and can decline analysis entirely without losing access to support.",
    },
    {
      number: '02',
      title: 'Tell your story',
      description:
        'Type or speak in your own words, in English or Hindi. Voice input is transcribed directly in your browser — nothing is uploaded just to convert speech to text.',
    },
    {
      number: '03',
      title: 'AI analysis',
      description:
        "Your transcript is analyzed for emotional intensity, sentiment, and narrative severity, producing a Stress Vulnerability Index (SVI) from 0–100. A separate, deterministic safety check also scans for crisis-level language — this check can't be reasoned around by the AI model.",
    },
    {
      number: '04',
      title: 'Risk category assigned',
      description:
        'Your SVI score places you into Low, Moderate, High, or Critical — each with a clear, explained recommended next step, not just a number.',
    },
    {
      number: '05',
      title: 'Human review',
      description:
        'Every case appears on a counsellor dashboard, sorted by urgency. Critical cases are pinned to the top and flagged for immediate attention — but a human always makes the final call. SahAI never contacts police or emergency services automatically.',
    },
  ];

  return (
    <div className="min-h-screen bg-white flex flex-col">
      {/* Navbar */}
      <nav className="border-b border-gray-200">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2 cursor-pointer" onClick={() => navigate('/')}>
            <div className="w-10 h-10 bg-blue-600 rounded-full flex items-center justify-center">
              <span className="text-white font-bold text-lg">S</span>
            </div>
            <span className="text-xl font-bold text-gray-900">SahAI</span>
          </div>
          <div className="flex items-center gap-6">
            <button onClick={() => navigate('/')} className="text-gray-600 hover:text-gray-900">
              Home
            </button>
            <button onClick={() => navigate('/psychiatrist/login')} className="text-gray-600 hover:text-blue-600 font-medium transition-colors">
              Psychiatrist Portal
            </button>
          </div>
        </div>
      </nav>

      {/* Main Content */}
      <div className="flex-1 px-6 py-16">
        <div className="max-w-3xl mx-auto">
          <p className="font-mono text-xs uppercase tracking-wider text-gray-400 mb-4">
            // the pipeline
          </p>
          <h1 className="text-4xl md:text-5xl font-extrabold text-gray-900 mb-6 leading-tight">
            From first word to<br />
            <span className="text-blue-600">the right response.</span>
          </h1>
          <p className="text-lg text-gray-600 mb-14 max-w-xl">
            Five steps, always with a person on the other end of the highest-stakes decisions.
          </p>

          <div className="space-y-10">
            {steps.map((step) => (
              <div key={step.number} className="flex gap-6">
                <div className="flex-shrink-0">
                  <div className="w-12 h-12 rounded-full bg-blue-50 border border-blue-100 flex items-center justify-center font-mono text-blue-600 font-bold text-sm">
                    {step.number}
                  </div>
                </div>
                <div>
                  <h3 className="text-xl font-bold text-gray-900 mb-2">{step.title}</h3>
                  <p className="text-gray-600 leading-relaxed">{step.description}</p>
                </div>
              </div>
            ))}
          </div>

          <div className="mt-14 bg-blue-50 border border-blue-100 rounded-xl p-6">
            <p className="text-sm font-semibold text-blue-900 mb-2">A note on accuracy</p>
            <p className="text-sm text-blue-800 leading-relaxed">
              SahAI's scoring is generated by an AI model and is not clinically validated. It is
              designed to help prioritize review, not to diagnose or make final decisions. Every
              Critical-risk case is reviewed by a human before any action is taken.
            </p>
          </div>

          <div className="mt-10 flex gap-4">
            <button onClick={() => navigate('/intake')} className="btn-primary px-6 py-3">
              Start Assessment →
            </button>
            <button onClick={() => navigate('/about')} className="btn-secondary px-6 py-3">
              About SahAI →
            </button>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="border-t border-gray-200 bg-gray-50 py-6">
        <div className="max-w-7xl mx-auto px-6 text-center text-sm text-gray-600">
          <p>
            Student prototype for Smart India Hackathon. Not affiliated with or a substitute for
            official NHAA 14566 services.
          </p>
        </div>
      </footer>
    </div>
  );
}
